import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './style.css'
import { Lato } from "next/font/google";
import { ReduxProvider } from "./redux/provider";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"], // choose what you need
  variable: "--font-lato",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable}}`}
      >
        <ReduxProvider>
          {children}
          <ToastContainer />
        </ReduxProvider>
      </body>
    </html>
  );
}
